coordinate:
    go build -buildmode=plugin ../mrapps/wc.go && sh -c 'rm -f mr-out*' && go run mrcoordinator.go pg-*.txt

work:
    go build -buildmode=plugin ../mrapps/wc.go && go run mrworker.go wc.so

